//! YouTube session cookies: capture, storage, and the two shapes consumers need.
//!
//! These cookies are full Google account credentials — anyone holding them is
//! signed in as the user, everywhere. So unlike the cloud OAuth tokens (which
//! sit in plaintext JSON under the app-data dir), they live in the OS credential
//! store: Keychain on macOS, Credential Manager on Windows, Secret Service on
//! Linux.
//!
//! Two consumers need two formats:
//!   * `ytmapi-rs` wants a `Cookie:` header string.
//!   * `yt-dlp` wants a Netscape `cookies.txt` file on disk.
//!
//! The file is the awkward one — it puts credentials back on disk, undoing the
//! keychain. [`CookieFile`] keeps that blast radius small: it writes to the OS
//! temp dir with `0600`, and deletes itself on drop.

use serde::{Deserialize, Serialize};
use std::io::Write;
use std::path::{Path, PathBuf};

/// Keychain coordinates. Matches the app's bundle id so the entry is
/// recognisable in Keychain Access.
const SERVICE: &str = "com.lwmuzik.hypemuzik";
const ACCOUNT: &str = "ytmusic-cookies";

/// Domains whose cookies matter. YT Music auth is split: the session lives on
/// `.youtube.com`, but `SAPISID` (which the API's auth hash derives from) is set
/// on `.google.com`. Capturing only one silently yields a signed-out client.
pub const COOKIE_DOMAINS: &[&str] = &["youtube.com", "google.com"];

/// Whether a cookie's domain is one we harvest from: `base` itself, or a
/// subdomain of it.
///
/// Matching on the dot boundary rather than a bare suffix is what keeps
/// `notyoutube.com` out — these are credentials, and they get written to a
/// `cookies.txt` for yt-dlp, so a loose match would hand them to a stranger.
pub fn wanted_domain(domain: &str) -> bool {
    let host = domain.strip_prefix('.').unwrap_or(domain);
    COOKIE_DOMAINS
        .iter()
        .any(|base| host == *base || host.ends_with(&format!(".{base}")))
}

/// Cookies that must be present for an authenticated YT Music session.
/// `SAPISID` has a `__Secure-3PAPISID` twin; either satisfies the requirement.
const REQUIRED_ANY: &[&[&str]] = &[
    &["SAPISID", "__Secure-3PAPISID"],
    &["SID", "__Secure-1PSID", "__Secure-3PSID"],
];

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct YtCookie {
    pub name: String,
    pub value: String,
    pub domain: String,
    pub path: String,
    /// Unix seconds. `None` is a session cookie.
    pub expires: Option<i64>,
    pub secure: bool,
    pub http_only: bool,
}

/// Builds the `Cookie:` header value for `ytmapi-rs`.
///
/// De-duplicates by name, keeping the first occurrence — the same name can
/// legitimately appear for `.youtube.com` and `.google.com`, and sending both
/// makes the API's auth hash fail to verify.
pub fn header(cookies: &[YtCookie]) -> String {
    let mut seen = std::collections::HashSet::new();
    cookies
        .iter()
        .filter(|c| seen.insert(c.name.as_str()))
        .map(|c| format!("{}={}", c.name, c.value))
        .collect::<Vec<_>>()
        .join("; ")
}

/// Renders a Netscape `cookies.txt`, the only cookie format yt-dlp accepts.
///
/// Tab-separated: `domain, include_subdomains, path, secure, expiry, name,
/// value`. HttpOnly cookies carry a `#HttpOnly_` domain prefix — it looks like a
/// comment but is load-bearing, and dropping it loses the session cookies.
pub fn netscape(cookies: &[YtCookie]) -> String {
    let mut out = String::from("# Netscape HTTP Cookie File\n# Generated by HypeMuzik. Do not edit.\n\n");
    for c in cookies {
        let domain = if c.http_only {
            format!("#HttpOnly_{}", c.domain)
        } else {
            c.domain.clone()
        };
        let include_subdomains = if c.domain.starts_with('.') { "TRUE" } else { "FALSE" };
        let secure = if c.secure { "TRUE" } else { "FALSE" };
        // 0 = session cookie in this format.
        let expiry = c.expires.unwrap_or(0);
        out.push_str(&format!(
            "{}\t{}\t{}\t{}\t{}\t{}\t{}\n",
            domain, include_subdomains, c.path, secure, expiry, c.name, c.value
        ));
    }
    out
}

/// Whether this cookie set looks like a signed-in session.
///
/// Checked at capture time so a half-finished login surfaces immediately rather
/// than as a confusing empty playlist list later.
pub fn is_signed_in(cookies: &[YtCookie]) -> bool {
    REQUIRED_ANY.iter().all(|group| {
        group
            .iter()
            .any(|want| cookies.iter().any(|c| c.name == *want && !c.value.is_empty()))
    })
}

/// Drops cookies that have already expired.
///
/// `now` is injected rather than read here so the filter is testable.
pub fn prune_expired(cookies: Vec<YtCookie>, now: i64) -> Vec<YtCookie> {
    cookies
        .into_iter()
        .filter(|c| c.expires.is_none_or(|e| e > now))
        .collect()
}

pub fn now_secs() -> i64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs() as i64)
        .unwrap_or(0)
}

/* ---- keychain storage ---- */

fn entry() -> Result<keyring::Entry, String> {
    keyring::Entry::new(SERVICE, ACCOUNT).map_err(|e| format!("keychain unavailable: {e}"))
}

/// Persists cookies to the OS credential store.
pub fn save(cookies: &[YtCookie]) -> Result<(), String> {
    let json = serde_json::to_string(cookies).map_err(|e| e.to_string())?;
    entry()?
        .set_password(&json)
        .map_err(|e| format!("could not save credentials: {e}"))
}

/// Loads cookies, or `None` when nothing is stored (i.e. signed out).
pub fn load() -> Result<Option<Vec<YtCookie>>, String> {
    match entry()?.get_password() {
        Ok(json) => serde_json::from_str(&json)
            .map(Some)
            .map_err(|e| format!("stored credentials are corrupt: {e}")),
        Err(keyring::Error::NoEntry) => Ok(None),
        Err(e) => Err(format!("could not read credentials: {e}")),
    }
}

/// Removes stored cookies. Succeeds when there was nothing to remove.
pub fn clear() -> Result<(), String> {
    match entry()?.delete_credential() {
        Ok(()) | Err(keyring::Error::NoEntry) => Ok(()),
        Err(e) => Err(format!("could not clear credentials: {e}")),
    }
}

/* ---- ephemeral cookies.txt for yt-dlp ---- */

/// A `cookies.txt` that deletes itself on drop.
///
/// yt-dlp only takes cookies as a file path, so credentials have to touch disk
/// for the length of a call. Keeping it in the temp dir at `0600` and unlinking
/// on drop bounds that exposure to the process lifetime, rather than leaving a
/// durable plaintext copy next to the app's data.
pub struct CookieFile {
    path: PathBuf,
}

impl CookieFile {
    /// Writes `cookies` to a private temp file.
    pub fn new(cookies: &[YtCookie]) -> Result<Self, String> {
        let path = std::env::temp_dir().join(format!(
            "hm-ytm-cookies-{}-{}.txt",
            std::process::id(),
            now_secs()
        ));
        let mut file = std::fs::File::create(&path).map_err(|e| e.to_string())?;
        // Narrow the mode before writing, so the contents are never briefly
        // world-readable.
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            file.set_permissions(std::fs::Permissions::from_mode(0o600))
                .map_err(|e| e.to_string())?;
        }
        file.write_all(netscape(cookies).as_bytes())
            .map_err(|e| e.to_string())?;
        file.flush().map_err(|e| e.to_string())?;
        Ok(Self { path })
    }

    pub fn path(&self) -> &Path {
        &self.path
    }
}

impl Drop for CookieFile {
    fn drop(&mut self) {
        let _ = std::fs::remove_file(&self.path);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn cookie(name: &str, value: &str) -> YtCookie {
        YtCookie {
            name: name.to_string(),
            value: value.to_string(),
            domain: ".youtube.com".to_string(),
            path: "/".to_string(),
            expires: Some(4_000_000_000),
            secure: true,
            http_only: false,
        }
    }

    #[test]
    fn header_joins_pairs() {
        let c = vec![cookie("SID", "abc"), cookie("SAPISID", "def")];
        assert_eq!(header(&c), "SID=abc; SAPISID=def");
    }

    #[test]
    fn header_dedups_by_name() {
        // Same cookie present for .youtube.com and .google.com — sending both
        // breaks the API's SAPISIDHASH verification.
        let mut dup = cookie("SAPISID", "second");
        dup.domain = ".google.com".to_string();
        let c = vec![cookie("SAPISID", "first"), dup];
        assert_eq!(header(&c), "SAPISID=first");
    }

    #[test]
    fn netscape_has_expected_columns() {
        let out = netscape(&[cookie("SID", "abc")]);
        let line = out.lines().find(|l| l.contains("SID")).unwrap();
        let cols: Vec<&str> = line.split('\t').collect();
        assert_eq!(cols.len(), 7);
        assert_eq!(cols[0], ".youtube.com");
        assert_eq!(cols[1], "TRUE"); // leading dot => include subdomains
        assert_eq!(cols[2], "/");
        assert_eq!(cols[3], "TRUE"); // secure
        assert_eq!(cols[4], "4000000000");
        assert_eq!(cols[5], "SID");
        assert_eq!(cols[6], "abc");
    }

    #[test]
    fn netscape_marks_http_only() {
        let mut c = cookie("SID", "abc");
        c.http_only = true;
        assert!(netscape(&[c]).contains("#HttpOnly_.youtube.com"));
    }

    #[test]
    fn netscape_session_cookie_expires_zero() {
        let mut c = cookie("SID", "abc");
        c.expires = None;
        let line = netscape(&[c]);
        assert!(line.contains("\t0\tSID\t"));
    }

    #[test]
    fn netscape_host_only_cookie_excludes_subdomains() {
        let mut c = cookie("SID", "abc");
        c.domain = "music.youtube.com".to_string();
        let line = netscape(&[c]);
        assert!(line.contains("music.youtube.com\tFALSE\t"));
    }

    #[test]
    fn wanted_domain_accepts_the_domains_the_session_lives_on() {
        // The cookies that carry the session are domain cookies on the apex.
        // These are exactly the ones the old `cookies_for_url` capture dropped.
        assert!(wanted_domain(".youtube.com"));
        assert!(wanted_domain(".google.com"));
        assert!(wanted_domain("youtube.com"));
        assert!(wanted_domain("google.com"));
    }

    #[test]
    fn wanted_domain_accepts_subdomains() {
        assert!(wanted_domain("music.youtube.com"));
        assert!(wanted_domain("accounts.google.com"));
        assert!(wanted_domain(".www.youtube.com"));
    }

    #[test]
    fn wanted_domain_rejects_lookalikes() {
        // Matching on a bare suffix would admit these, and they'd be handed to
        // yt-dlp in a cookies.txt — a credential leak to an unrelated host.
        assert!(!wanted_domain("notyoutube.com"));
        assert!(!wanted_domain("evil-google.com"));
        assert!(!wanted_domain("youtube.com.evil.net"));
        assert!(!wanted_domain("example.com"));
        assert!(!wanted_domain(""));
    }

    #[test]
    fn signed_in_needs_both_groups() {
        assert!(is_signed_in(&[cookie("SAPISID", "x"), cookie("SID", "y")]));
        // Either twin satisfies its group.
        assert!(is_signed_in(&[
            cookie("__Secure-3PAPISID", "x"),
            cookie("__Secure-1PSID", "y")
        ]));
    }

    #[test]
    fn signed_out_when_a_group_is_missing() {
        assert!(!is_signed_in(&[cookie("SAPISID", "x")]));
        assert!(!is_signed_in(&[cookie("SID", "y")]));
        assert!(!is_signed_in(&[]));
    }

    #[test]
    fn empty_value_does_not_count_as_signed_in() {
        assert!(!is_signed_in(&[cookie("SAPISID", ""), cookie("SID", "")]));
    }

    #[test]
    fn prune_drops_expired_keeps_session() {
        let mut expired = cookie("OLD", "x");
        expired.expires = Some(100);
        let mut session = cookie("SESS", "y");
        session.expires = None;
        let kept = prune_expired(vec![expired, session, cookie("SID", "z")], 1_000);
        let names: Vec<&str> = kept.iter().map(|c| c.name.as_str()).collect();
        assert_eq!(names, vec!["SESS", "SID"]);
    }

    /// Exercises the real OS credential store. Ignored by default: it touches
    /// the user's keychain, and on Linux CI there's usually no Secret Service
    /// running. Run with `cargo test -p hm-ytmusic -- --ignored` to check the
    /// platform backend actually works before trusting sign-in to it.
    #[test]
    #[ignore = "touches the real OS keychain"]
    fn keychain_round_trips() {
        let c = vec![cookie("SAPISID", "round-trip-value"), cookie("SID", "y")];

        save(&c).expect("save to keychain");
        let loaded = load().expect("load from keychain").expect("entry present");
        assert_eq!(loaded, c);

        clear().expect("clear keychain");
        assert!(load().expect("load after clear").is_none());
        // Clearing a missing entry must be a no-op, not an error — sign-out
        // shouldn't fail just because there was nothing stored.
        clear().expect("clear is idempotent");
    }

    #[test]
    fn cookie_file_writes_then_deletes() {
        let path;
        {
            let f = CookieFile::new(&[cookie("SID", "abc")]).unwrap();
            path = f.path().to_path_buf();
            let body = std::fs::read_to_string(&path).unwrap();
            assert!(body.contains("SID\tabc"));
            #[cfg(unix)]
            {
                use std::os::unix::fs::PermissionsExt;
                let mode = std::fs::metadata(&path).unwrap().permissions().mode();
                assert_eq!(mode & 0o777, 0o600, "cookie file must not be readable by others");
            }
        }
        assert!(!path.exists(), "cookie file must be removed on drop");
    }
}
